# Generated by Django 4.0.6 on 2022-08-03 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rev_count', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_Name', models.CharField(max_length=250)),
                ('APX_Name', models.CharField(max_length=100)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rev_count.r1')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rev_count.v1')),
            ],
        ),
    ]
