# Generated by Django 4.0.6 on 2022-08-03 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rev_count', '0002_reviews_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField()),
                ('date', models.DateField()),
                ('ratings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_Name', models.CharField(max_length=250)),
                ('APX_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='reviews_rating',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='reviews_rating',
            name='view',
        ),
        migrations.DeleteModel(
            name='r1',
        ),
        migrations.DeleteModel(
            name='reviews_rating',
        ),
        migrations.DeleteModel(
            name='v1',
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rev_count.storedetails'),
        ),
    ]
